INSERT INTO gym(Gname, location, region) VALUES ('Pewter City Gym', 'Pewter City', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Cerulean City Gym', 'Cerulean City', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Vermilion City Gym', 'Vermilion City', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Celadon City Gym', 'Celadon City', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Fuchsia City Gym', 'Fuchsia City', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Saffron City Gym', 'Saffron City', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Cinnabar Island Gym', 'Cinnabar Island', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Seafoam Islands Gym', 'Seafoam Islands', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Viridian City Gym', 'Viridian City', 'Kanto');
