INSERT INTO gym(Gname, location, region) VALUES ('Gym 1', 'Pewter city', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Gym 2', 'Cerulean city', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Gym 3', 'Vermilion city', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Gym 4', 'Celadon city', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Gym 5', 'Fuchsia city', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Gym 6', 'Saffron city', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Gym 7', 'Cinnabar island', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Gym 8', 'Seafoam islands', 'Kanto');
INSERT INTO gym(Gname, location, region) VALUES ('Gym 9', 'Viridian city', 'Kanto');
