INSERT INTO badGuy(CName, Affiliation) VALUES ('Katie', 'Rocket');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Danae', 'Aqua');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Holly', 'Galactic');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Erin', 'Rocket');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Amanda', 'Plasma');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Brock', 'Pewter');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Gary', 'Viridian');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Lt. Surge', 'Vermilion');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Sabrina', 'Saffron');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Erika', 'Celadon');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Koga', 'Fuschia');
INSERT INTO badGuy(CName, Affiliation) VALUES ('Blaine', 'Cinnabar');