INSERT INTO hasAttack(AttackName, ID) VALUES ('Gust', 12);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Gust', 16);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Gust', 17);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Gust', 18);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Gust', 41);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Gust', 42);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Gust', 49);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Gust', 144);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Gust', 146);

INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 16);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 17);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 18);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 27);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 28);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 50);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 51);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 74);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 75);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 76);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 83);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 111);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 112);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 133);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 134);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 136);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 138);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 139);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 140);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Sand Attack', 141);

INSERT INTO hasAttack(AttackName, ID) VALUES ('Horn Attack', 32);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Horn Attack', 33);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Horn Attack', 34);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Horn Attack', 111);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Horn Attack', 112);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Horn Attack', 118);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Horn Attack', 119);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Horn Attack', 128);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Horn Attack', 138);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Horn Attack', 139);

INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 1);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 2);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 3);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 7);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 8);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 9);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 10);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 12);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 16);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 17);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 18);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 19);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 20);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 29);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 30);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 31);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 32);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 33);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 34);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 35);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 36);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 37);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 38);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 48);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 49);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 58);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 59);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 66);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 67);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 68);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 74);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 75);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 76);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 77);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 78);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 79);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 80);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 81);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 82);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 90);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 91);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 95);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 100);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 101);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 106);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 107);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 108);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 109);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 110);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 111);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 112);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 113);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 120);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 121);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 126);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 128);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 129);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 130);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 133);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 134);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 135);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 136);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 137);
INSERT INTO hasAttack(AttackName, ID) VALUES ('Tackle', 143);

