set define off

INSERT INTO episode(title, EpisodeNumber) VALUES ('Pokémon I Choose You!', 1);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Pokémon Emergency!', 2);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Ash Catches a Pokémon', 3);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Challenge of the Samurai', 4);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Showdown in Pewter City', 5);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Clefairy and the Moon Stone', 6);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Water Flowers of Cerulean City', 7);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Path to the Pokémon League', 8);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The School of Hard Knocks', 9);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Bulbasaur and the Hidden Village', 10);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Charmander - The Stray Pokémon', 11);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Here Comes the Squirtle Squad', 12);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Mystery at the Lighthouse', 13);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Electric Shock Showdown', 14);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Battle Aboard the St. Anne', 15);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Pokémon Shipwreck', 16);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Island of the Giant Pokémon', 17);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Beauty and the Beach', 18);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Tentacool & Tentacruel', 19);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Ghost of Maidens Peak', 20);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Bye Bye Butterfree', 21);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Abra and the Psychic Showdown (Part 1)', 22);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Tower of Terror (Part 2)', 23);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Haunter vs. Kadabra (Part 3)', 24);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Primeape Goes Bananas', 25);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Pokémon Scent-sation!', 26);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Hypnos Naptime', 27);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Pokémon Fashion Flas', 28);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Punchy Pokémon', 29);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Sparks Fly for Magnemite', 30);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Dig Those Diglett!', 31);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Ninja-Poké Showdown', 32);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Flame Pokémon-athon!', 33);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Kangaskhan Kid', 34);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Legend of Dratini', 35);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Bridge Bike Gang', 36);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Dittos Mysterious Mansion', 37);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Electric Soldier Porygon', 38);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Pikachus Goodbye', 39);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Battling Eevee Brothers', 40);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Wake Up Snorlax!', 41);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Showdown at Dark City', 42);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The March of the Exeggutor Squad', 43);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Problem with Paras', 44);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Song of Jigglypuff', 45);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Attack of the Prehistoric Pokémon', 46);
INSERT INTO episode(title, EpisodeNumber) VALUES ('A Chansey Operation', 47);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Holy Matrimony!', 48);
INSERT INTO episode(title, EpisodeNumber) VALUES ('So Near, Yet So Farfetchd', 49);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Who Gets to Keep Togepi?', 50);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Bulbasaurs Mysterious Garden', 51);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Princess vs. Princess', 52);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Purr-fect Hero', 53);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Case of the K-9 Caper!', 54);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Pokémon Paparazzi', 55);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Ultimate Test', 56);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Breeding Center Secret', 57);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Riddle Me This', 58);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Volcanic Panic', 59);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Beach Blank-Out Blastoise', 60);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Misty Mermaid', 61);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Clefairy Tales', 62);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Battle of the Badge', 63);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Its Mr. Mime Time!', 64);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Holiday Hi-Jynx', 65);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Snow Way Out', 66);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Showdown at the Po-ké Corral', 67);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Evolution Solution', 68);
INSERT INTO episode(title, EpisodeNumber) VALUES ('The Pi-Kahuna', 69);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Make Room for Gloom', 70);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Lights, Camera, Quack-tion!', 71);
INSERT INTO episode(title, EpisodeNumber) VALUES ('Go West, Young Meowth', 72);
INSERT INTO episode(title, EpisodeNumber) VALUES ('To Master the Onixpected!', 73);
INSERT INTO epsiode(title, EpisodeNumber) VALUES ('The Ancient Puzzle of Pokémopolis', 74);
INSERT INTO epsiode(title, EpisodeNumber) VALUES ('Bad to the Bone!', 75);
INSERT INTO epsiode(title, EpisodeNumber) VALUES ('All Fired Up!', 76);
INSERT INTO epsiode(title, EpisodeNumber) VALUES ('Round One: Begin!', 77);
INSERT INTO epsiode(title, EpisodeNumber) VALUES ('Fire and Ice', 78);
INSERT INTO epsiode(title, EpisodeNumber) VALUES ('The Fourth Round Rumble', 79);
INSERT INTO epsiode(title, EpisodeNumber) VALUES ('A Friend in Deed', 80);
INSERT INTO epsiode(title, EpisodeNumber) VALUES ('Friend and Foe Alike', 81);
INSERT INTO epsiode(title, EpisodeNumber) VALUES ('Friends to the End', 82);

