CREATE TABLE isType
	(id		INTEGER,
	TName		CHARACTER(50),
	PRIMARY KEY (id, TName),
	FOREIGN KEY (id)
    REFERENCES Pokemon
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (TName)
    REFERENCES Type
    ON DELETE CASCADE
    ON UPDATE CASCADE);